core/urls.py
from django.urls import path

from product.views import categories_view, product_discount_view, category_detail_view
from .views import (
    base_view,
    about_view,
    blog_view,
    blog_post_detail_view,
    faq_view,
    delivery_view,
)

urlpatterns = [
    # Navigation
    path('', base_view, name='base'),
    path('about/', about_view, name='about'),
    # blog
    path('blog/', blog_view, name='blog'),
    path('blog/post/<int:id>', blog_post_detail_view, name='blog_detail'),
    # category
    path('categories/', categories_view, name='categories'),
    path('category/discount/', product_discount_view, name='product_discount'),
    path('category/<str:slug>/', category_detail_view, name='category_detail'),
    # faq
    path('faq/', faq_view, name='faq_view'),
    # delivery
    path('delivery/', delivery_view, name='delivery_view'),
]

order/urls.py
# Cart
from django.urls import path

from order.views import cart_view, add_to_cart_view, delete_from_cart_view, change_qty_cart_view, checkout_view, \
    make_order_view

urlpatterns = [
    path('cart/', cart_view, name='cart'),
    path('add-to-cart/<str:category>/<str:slug>/', add_to_cart_view, name='add_to_cart'),
    path('add-to-cart/<str:category>/<str:slug>/v<int:variant>/', add_to_cart_view, name='add_to_cart'),
    path('remove-from-cart/<str:category>/<str:slug>/', delete_from_cart_view, name='delete_from_cart'),
    path('remove-from-cart/<str:category>/<str:slug>/v<int:variant>', delete_from_cart_view, name='delete_from_cart'),
    path('change-qty-cart/<str:category>/<str:slug>/', change_qty_cart_view, name='change_qty_cart'),
    path('change-qty-cart/<str:category>/<str:slug>/v<int:variant>', change_qty_cart_view, name='change_qty_cart'),
    # Orders
    path('checkout/', checkout_view, name='checkout'),
    path('make-order/', make_order_view, name='make_order'),
]

product/urls.py
from django.urls import path

from product.views import product_detail_view, search_view, product_sizes, product_price

urlpatterns = [
    path('<str:category>/<str:slug>/', product_detail_view, name='product_detail'),
    path('<str:category>/<str:slug>/c<int:color>/', product_detail_view, name='product_variant'),
    path('<str:category>/<str:slug>/v<int:variant>/', product_detail_view, name='product_variant'),
    path('<str:category>/<str:slug>/c<int:color>/v<int:variant>/', product_detail_view, name='product_variant'),
    path('sizes/', product_sizes, name='product_sizes'),
    path('price/', product_price, name='product_price'),
    path('search/', search_view, name='search'),
]

shop/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # Extensions
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # Custom
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include(('user.urls', 'user'), namespace="profiles")),
    path('order/', include(('order.urls', 'order'), namespace="orders")),
    path('product/', include(('product.urls', 'product'), namespace="products")),
    # Extensions
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('_nested_admin/', include('nested_admin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import profile_view


urlpatterns = [
    # User
    path('', profile_view, name='profile'),
]

templates/include/blog_card.html
<div class="blog-post__card">
    <div class="blog-post__card-body">
        <div class="blog-post__card-body--post-img">
            <a href="{% url 'blog_detail' id=post.id %}">
                <img src="{{ post.preview_img.url }}" alt="">
            </a>
        </div>
        <div class="blog-post__card-post-info">
            <div class="blog-post__card-body-date">
                <p>{{ post.date_created }}</p>
            </div>
            <div class="blog-post__card-body-title">
                <h4>{{ post.title }}</h4>
            </div>
            <div class="blog-post__card-body-description">
                <p class="text--brown">{{ post.preview_content | safe | truncatechars:120 }}</p>
            </div>
            <div class="blog-post__card-post-info__btn-container">
                <a href="{% url 'blog_detail' id=post.id %}">
                    <button class="blog-post__card-post-info__btn">
                        READ MORE
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>

templates/include/categories_navbar.html
{% load static %}

<div class="navbar-container">
    <div class="navbar">
        <ul class="navbar-categories">
            <li class="navbar-categories__item">
                <a href="{% url 'base' %}" class="navbar-categories__item-link">
                    HOME
                </a>
            </li>
            <li class="navbar-categories__item">
                <a href="{% url 'product_discount' %}" class="navbar-categories__item-link text--red">
                    DISCOUNTS
                </a>
            </li>
            <li class="navbar-categories__item">
                <a href="{% url 'categories' %}" class="navbar-categories__item-link">
                    CATEGORIES
                </a>
            </li>
            <li class="navbar-categories__item">
                <a href={% url 'blog' %}#" class="navbar-categories__item-link">
                    BLOG
                </a>
            </li>
            <li class="navbar-categories__item">
                <a href="{% url 'about' %}" class="navbar-categories__item-link">
                    ABOUT
                </a>
            </li>
            <li class="navbar-categories__item">
                <a href="{% url 'faq_view' %}" class="navbar-categories__item-link">
                    FAQ
                </a>
            </li>
        </ul>
    </div>
    {% if user.is_authenticated %}
        {% include 'include/profile_dropdown.html' %}
    {% endif %}
</div>

templates/include/category_card.html
<div class="category__card">
    <a href="{{ category.get_absolute_url }}">
        <div class="category__card-background">
            {% if category.category_photo %}
                <img src="{{ category.category_photo.url }}" alt="">
            {% else %}
                <img src="https://images.unsplash.com/photo-1539533018447-63fcce2678e3?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" alt="">
            {% endif %}
        </div>
        <div class="category__card-body">
            <h3 class="">{{ category.name.upper }}</h3>
        </div>
    </a>
</div>

templates/include/filter.html
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/extensions/nouislider.css' %}">
{% endblock %}

<div class="filter-form">

    <div class="filter-form-header">
        <h4>Filter</h4>
        <button class="close__filter-btn"></button>
    </div>

    <form action="" method="GET" class="filter-form__filters">
        {% csrf_token %}

        <div class="filter-form__filters-col">
            <div class="filter-form__filters-wrapper">
                <span class="{{ filter_form.brand.name }}">{{ filter_form.brand.label }}</span>
                {{ filter_form.brand }}
            </div>
        </div>

        <div class="filter-form__filters-price">

            <div class="price-slider-horizontal"></div>
            <div class="price-minmax-container">
                {{ filter_form.price_min }}
                {{ filter_form.price_max }}
            </div>
            <div class="filter-form__filters-col">

            </div>
            <div class="filter-form__filters-col">

            </div>

        </div>

        {% for field in filter_form.visible_fields %}

            {% if field.name == "price_max" or field.name == "price_min" or field.name == "brand" %}
            {% else %}
                <div class="filter-form__filters-col">
                    <div class="filter-form__filters-wrapper">
                        <span class="{{ field.name }}">{{ field.label }}</span>
                        {{ field }}
                    </div>
                </div>
            {% endif %}

        {% endfor %}

        {% for num in category_products.paginator.page_range %}

            {% if category_products.number == num %}

                <input type="hidden" value="{{ num }}" name="page" />

            {% endif %}

        {% endfor %}

        <input type="submit" class="filter-form__filters-submit-btn" value="Submit">
    </form>
</div>

templates/include/footer.html
{% load static %}


<div class="footer-wrapper">
    <div class="footer-block">
        <ul class="footer-actions">
            <li class="footer-actions__item">
                <a href="{% url 'blog' %}" class="footer-actions__item-link text--brownAndWhite-outlined">Blog</a>
            </li>
            <li class="footer-actions__item">
                <a href="{% url 'delivery_view' %}" class="footer-actions__item-link text--brownAndWhite-outlined">Shipping & Payment</a>
            </li>
            <li class="footer-actions__item">
                <a href="{% url 'faq_view' %}" class="footer-actions__item-link text--brownAndWhite-outlined">FAQ</a>
            </li>
            <li class="footer-actions__item">
                <a href="{% url 'about' %}" class="footer-actions__item-link text--brownAndWhite-outlined">About</a>
            </li>
        </ul>
    </div>
    <div class="footer-wrapper__background-circle footer-wrapper__background-circle-left"></div>
    <div class="footer-wrapper__background-circle footer-wrapper__background-circle-right"></div>
</div>

templates/include/goods_card.html
<div class="goods__card">
    <a href="{{ trend_product.product.get_absolute_url }}">
        <div class="goods__card-background">
            <img src="{{ trend_product.banner_img.url }}"
                 alt=""
                 class="goods__card-background-img">
        </div>
        <div class="goods__card-body">
            <div class="goods__card-body-header">
                <h3>{{ trend_product.product.title }}</h3>
            </div>
            <div class="goods__card-body-description">
                <p>{{ trend_product.content }}</p>
            </div>
            <div class="goods__card-body-footer">
                {% if trend_product.product.discount_price %}
                    <div class="goods__card-body-footer-price--with-discount">
                        <p><del>{{ trend_product.product.price }}$</del></p>
                    </div>
                    <div class="goods__card-body-footer-price--discount text--red ">
                        <p>{{ trend_product.product.discount_price }}$</p>
                    </div>
                {% else %}
                    <div class="goods__card-body-footer-price">
                        <p>{{ trend_product.product.price }}$</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </a>
</div>

templates/include/header.html
{% load static %}


<div class="header-container">
    <!-- Header -->
    <div class="logo-container">
        <img src="{% static 'icons/logo.png' %}"></img>
    </div>
    <div class="searchbar-container">
        <form action="{% url 'products:search' %}" method="GET" class="search-form">
            <div class="search-form__input-wrapper">
                <input type="text" class="search-form__input" name="search" value="{{ query }}">
            </div>
        </form>
    </div>
    <div class="userBar-container">
        <ul class="header-actions">
            <li class="header-actions__item header-actions__item-cart">
                <a class="header__button" href="{% url 'orders:cart' %}">
                    <img src="{% static 'icons/shopping_cart-24px.svg' %}" class="material-icons material-icons-outlined" alt="">
                    {% if total_products %}
                        <span class="counter counter--red">{{ total_products }}</span>
                    {% endif %}
                </a>
            </li>
            <li class="header-actions__item header-actions__item-profile">
                {% if not user.is_authenticated %}
                    <a class="header__button" href="{% url 'account_login' %}">
                        <img src="{% static 'icons/account_circle-24px.svg' %}" class="material-icons material-icons-outlined" alt="">
                        <span class="online-state counter--red">0</span>
                    </a>
                {% else %}
                    <div class="header__button--notClickable">
                        <img src="{% static 'icons/account_circle-24px.svg' %}" class="material-icons material-icons-outlined" alt="">
                        <span class="online-state counter--green">0</span>
                    </div>
                {% endif %}
            </li>
            <li class="header-actions__item header-actions__item-menu">
                <a href="javascript:void(0);" class="header__button" onclick="myFunction()">
                    <img src="{% static 'icons/menu_white_24dp.svg' %}" class="material-icons material-icons-outlined" alt="">
                </a>
            </li>
        </ul>
    </div>
    <!-- /Header -->
</div>


{% block js %}
    <script src="{% static 'js/navbar.js' %}"></script>
{% endblock %}

templates/include/order_card.html
<div class="profile-products__card">
    <div class="profile-products__card-body">
        <div class="profile-products__card-body__product-info">
            <div class="profile-products__card-body-info">
                <div class="card-body-info--col">
                    <h4>Order number</h4>
                    <p>{{ order.id }}</p>
                </div>
                <div class="card-body-info--col">
                    <h4>Date</h4>
                    <p>{{ order.date_order }}</p>
                </div>
                <div class="card-body-info--col">
                    <h4>Status</h4>
                    {% if order.status == 'new' %}
                        <p> New </p>
                    {% elif order.status == 'in_progress' %}
                        <p> In processing </p>
                    {% elif order.status == 'ready' %}
                        <p> Ready </p>
                    {% elif order.status == 'complete' %}
                        <p> Completed </p>
                    {% endif %}
                </div>
                <div class="card-body-info--col">
                    <h4>Quantity</h4>
                    <p>{{ order.cart.total_products }}</p>
                </div>
                <div class="card-body-info--col">
                    <h4>Amount</h4>
                    <p>{{ order.cart.final_price }}</p>
                </div>
            </div>
            <div class="profile-products__card-body-total-sum">
                <button class="profile__summary__order-button"
                        data-toggle="modal"
                        data-target="#exampleModal-{{ order.id }}">
                    MORE
                </button>
            </div>
        </div>
    </div>
</div>

templates/include/order_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel-{{ order.id }}" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel-{{ order.id }}">Детали заказа</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4 class="modal-title">Товар</h4>
                <table class="table">
                    <thead>
                    <tr>
                        <td>Image</td>
                        <td>Name</td>
                        <td>Price</td>
                        <td>Quantity</td>
                        <td>Total price</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product_cart in order.cart.products.all %}
                        <tr>
                            <td class="img-fluid modal-order__img">
                                <img src="{{ product_cart.product.get_main_img.url }}" alt=""
                                     class="modal-order__img">
                            </td>
                            <td>
                                <a href="{{ product_cart.product.get_absolute_url }}">{{ product_cart.product.title }}</a>
                            </td>
                            <td>
                            {% if product_cart.variant %}
                                {% if product_cart.variant.discount_price %}
                                    <span class="mr-1">
                                        <del>Price: {{ product_cart.variant.price }} грн.</del>
                                    </span>
                                    <p>Price: {{ product_cart.variant.discount_price }}</p>
                                {% else %}
                                    <p>Price: {{ product_cart.variant.price }}</p>
                                {% endif %}
                                </td>
                            {% else %}
                                {% if product_cart.product.discount_price %}
                                    <span class="mr-1">
                                        <del>Price: {{ product_cart.product.price }} грн.</del>
                                    </span>
                                    <p>Price: {{ product_cart.product.discount_price }}</p>
                                {% else %}
                                    <p>Price: {{ product_cart.product.price }}</p>
                                {% endif %}
                                </td>
                            {% endif %}
                            <td>{{ product_cart.qty }}</td>
                            <td>{{ product_cart.final_price }} грн.</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="2"></td>
                        <td>Total:</td>
                        <td>{{ order.cart.total_products }}</td>
                        <td>{{ order.cart.final_price }}</td>
                    </tr>
                    </tbody>
                </table>
                <hr>
                <h4 class="text-center">Дополнительная информация</h4>
                <p>First name: {{ order.first_name }}</p>
                <p>Last name: {{ order.last_name }}</p>
                <p>Phone: {{ order.phone }}</p>
                <p>City: {{ order.shipping_address.city }}</p>
                <p>Region: {{ order.shipping_address.region }}</p>
                <p>Street: {{ order.shipping_address.address }}</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/include/pagination.html
{% load tags_extras %}

<div class="pagination">
    {% if queryset.has_previous %}

        <a href="?{% url_replace page=1 %}">
            <button class="pagination-number">1</button>
        </a>

        <a href="?{% url_replace page=queryset.previous_page_number %}">
            <button class="pagination-action--prev"></button>
        </a>

        {% if queryset.number != 2 and queryset.number != 3 %}
            <p>...</p>
        {% endif %}

    {% endif %}


    {% for num in queryset.paginator.page_range %}

        {% if queryset.number == num %}

            <span class="pagination-number pagination-current">{{ num }}</span>

        {% elif num > queryset.number|add:'-2' and num < queryset.number|add:'2' %}

            {% if num == 1 or num == queryset.paginator.num_pages %}
            {% else %}
                <a class="pagination-number" href="?{% url_replace page=num %}">{{ num }}</a>
            {% endif %}

        {% endif %}

    {% endfor %}


    {% if queryset.has_next %}

        {% if queryset.number != queryset.paginator.num_pages|add:'-3' and queryset.number != queryset.paginator.num_pages|add:'-2' %}
        {% else %}
            <p>...</p>
        {% endif %}

        <a href="?{% url_replace page=queryset.next_page_number %}">
            <button class="pagination-action--next "></button>
        </a>
        <a href="?{% url_replace page=queryset.paginator.num_pages %}">
            <button class="pagination-number">{{ queryset.paginator.num_pages }}</button>
        </a>

    {% endif %}
</div>

templates/include/pagination_search.html
<div class="pagination">
    {% if queryset.has_previous %}

        <a href="?page={{ queryset.previous_page_number }}&search={{ search }}">
            <button class="pagination-action--prev"></button>
        </a>
        <a href="?page=1&search={{ search }}">
            <button class="">1</button>
        </a>

    {% endif %}

    {% for num in queryset.paginator.page_range %}

        {% if queryset.number == num %}

            <span class="pagination-number pagination-current">{{ num }}</span>

        {% elif num > queryset|add:'-3' and num > queryset.number|add:'3' %}

            <a class="pagination-number" href="?page={{ num }}&search={{ search }}">{{ num }}</a>

        {% endif %}

    {% endfor %}

    {% if queryset.has_next %}

        <a href="?page={{ queryset.next_page_number }}&search={{ search }}">
            <button class="pagination-action--next"></button>
        </a>
        <a href="?page={{ queryset.paginator.num_pages }}&search={{ search }}">
            <button>{{ queryset.paginator.num_pages }}</button>
        </a>
    {% endif %}
</div>

templates/include/popular_card.html
<div class="popular__card">
    <a href="{{ popular_product.get_absolute_url }}">
        <div class="popular__card-background">
            <img src="{{ popular_product.get_main_img.url }}"
                 alt=""
                 class="popular__card-background-img">
        </div>
        <div class="popular__card-body">
            <div class="popular__card-body-header">
                <h3>{{ popular_product.title }}</h3>
            </div>
            <div class="popular__card-body-footer">
                {% if popular_product.discount_price %}
                    <div class="goods__card-body-footer-price--with-discount">
                        <p><del>{{ popular_product.price }}$</del></p>
                    </div>
                    <div class="goods__card-body-footer-price--discount text--red ">
                        <p>{{ popular_product.discount_price }}$</p>
                    </div>
                {% else %}
                    <div class="goods__card-body-footer-price">
                        <p>{{ popular_product.price }}$</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </a>
</div>

templates/include/product_cart_card.html
<div class="cart-products__card">
    <div class="cart-products__card-body">

        {% if cart_product.variant %}
            <div class="cart-products__card-body--product-img">
                <a href="" class="cart-img-link d-block">
                    {% if cart_product.variant.image %}
                        <img class="img-fluid" src="{{ cart_product.variant.image }}" alt="">
                    {% else %}
                        <img class="img-fluid" src="{{ cart_product.product.get_main_img.url }}" alt="">
                    {% endif %}
                </a>
            </div>
            <div class="cart-products__card-body__product-info">
                <div class="cart-products__card-body-title">
                    <h4>{{ cart_product.variant.title }}</h4>
                </div>

                <div class="cart-products__card-body-counter">
{#                    <form action="{% url 'orders:change_qty_cart' category=cart_product.product.category.slug slug=cart_product.product.slug variant=cart_product.variant.id %}" method="Post">#}
{#                        {% csrf_token %}#}
{#                        <div class="counter-product">#}
{#                            <button class="counter-product--minus"#}
{#                                    type="button"#}
{#                                    onclick="this.nextElementSibling.stepDown(); this.nextElementSibling.onchange();">-</button>#}
{#                            <input type="number"#}
{#                                   class="form-control"#}
{#                                   name="qty"#}
{#                                   min="1"#}
{#                                   value="{{ cart_product.qty }}"#}
{#                                   readonly>#}
{#                            <button class="counter-product--plus"#}
{#                                    type="button"#}
{#                                    onclick="this.previousElementSibling.stepUp(); this.previousElementSibling.onchange();">+</button>#}
{#                        </div>#}
{#                        <input type="submit"#}
{#                               class="action-btn"#}
{#                               value="Изменить кол-во"#}
{#                               data-goods_id="{{ product.id }}"#}
{#                               data-action="addToCart">#}
{#                    </form>#}
                </div>

                <div class="cart-products__card-body-total-sum">
                    {% if cart_product.variant.discount_price %}
                        <p class="text--brown">{{ cart_product.variant.discount_price }}$</p>
                    {% else %}
                        <p class="text--brown">{{ cart_product.variant.price }}$</p>
                    {% endif %}
                </div>
                <a href="{% url 'orders:delete_from_cart' category=cart_product.product.category.slug slug=cart_product.product.slug variant=cart_product.variant.id %}">
                    <button class="cart-products__remove-button" data-goods_id="{{ product.id }}" data-action="remove"></button>
                </a>
            </div>
        {% else %}
            <div class="cart-products__card-body--product-img">
                <a href="" class="cart-img-link d-block">
                    <img class="img-fluid" src="{{ cart_product.product.get_main_img.url }}" alt="">
                </a>
            </div>
            <div class="cart-products__card-body__product-info">
                <div class="cart-products__card-body-title">
                    <h4>{{ cart_product.product.title }}</h4>
                </div>

                <div class="cart-products__card-body-counter">
{#                    <form action="{% url 'orders:change_qty_cart' category=cart_product.product.category.slug slug=cart_product.product.slug %}" method="Post">#}
{#                        {% csrf_token %}#}
{#                        <div class="counter-product">#}
{#                            <button class="counter-product--minus"#}
{#                                    type="button"#}
{#                                    onclick="this.nextElementSibling.stepDown(); this.nextElementSibling.onchange();">-</button>#}
{#                            <input type="number"#}
{#                                   class="form-control"#}
{#                                   name="qty"#}
{#                                   min="1"#}
{#                                   value="{{ cart_product.qty }}"#}
{#                                   readonly>#}
{#                            <button class="counter-product--plus"#}
{#                                    type="button"#}
{#                                    onclick="this.previousElementSibling.stepUp(); this.previousElementSibling.onchange();">+</button>#}
{#                        </div>#}
{#                        <input type="submit"#}
{#                               class="action-btn"#}
{#                               value="Изменить кол-во"#}
{#                               data-goods_id="{{ product.id }}"#}
{#                               data-action="addToCart">#}
{#                    </form>#}
                </div>

                <div class="cart-products__card-body-total-sum">
                    {% if cart_product.product.discount_price %}
                        <p class="text--brown">{{ cart_product.product.discount_price }} $</p>
                    {% else %}
                        <p class="text--brown">{{ cart_product.product.price }} $</p>
                    {% endif %}
                </div>
                <a href="{% url 'orders:delete_from_cart' category=cart_product.product.category.slug slug=cart_product.product.slug %}">
                    <button class="cart-products__remove-button" data-goods_id="{{ product.id }}" data-action="remove"></button>
                </a>
            </div>
        {% endif %}

    </div>
</div>

templates/include/profile_dropdown.html
<div class="profile-dropdown-container hidden">
    <ul>
        <li><a href="{% url 'profiles:profile' %}">My orders</a></li>
        <li><a href="{% url 'account_logout' %}">Log out</a></li>
    </ul>
</div>