core/urls.py
from django.urls import path

from product.views import categories_view, product_discount_view, category_detail_view
from .views import (
    base_view,
    about_view,
    blog_view,
    blog_post_detail_view,
    faq_view,
    delivery_view,
)

urlpatterns = [
    # Navigation
    path('', base_view, name='base'),
    path('about/', about_view, name='about'),
    # blog
    path('blog/', blog_view, name='blog'),
    path('blog/post/<int:id>', blog_post_detail_view, name='blog_detail'),
    # category
    path('categories/', categories_view, name='categories'),
    path('category/discount/', product_discount_view, name='product_discount'),
    path('category/<str:slug>/', category_detail_view, name='category_detail'),
    # faq
    path('faq/', faq_view, name='faq_view'),
    # delivery
    path('delivery/', delivery_view, name='delivery_view'),
]

order/urls.py
# Cart
from django.urls import path

from order.views import cart_view, add_to_cart_view, delete_from_cart_view, change_qty_cart_view, checkout_view, \
    make_order_view

urlpatterns = [
    path('cart/', cart_view, name='cart'),
    path('add-to-cart/<str:category>/<str:slug>/', add_to_cart_view, name='add_to_cart'),
    path('add-to-cart/<str:category>/<str:slug>/v<int:variant>/', add_to_cart_view, name='add_to_cart'),
    path('remove-from-cart/<str:category>/<str:slug>/', delete_from_cart_view, name='delete_from_cart'),
    path('remove-from-cart/<str:category>/<str:slug>/v<int:variant>', delete_from_cart_view, name='delete_from_cart'),
    path('change-qty-cart/<str:category>/<str:slug>/', change_qty_cart_view, name='change_qty_cart'),
    path('change-qty-cart/<str:category>/<str:slug>/v<int:variant>', change_qty_cart_view, name='change_qty_cart'),
    # Orders
    path('checkout/', checkout_view, name='checkout'),
    path('make-order/', make_order_view, name='make_order'),
]

product/urls.py
from django.urls import path

from product.views import product_detail_view, search_view, product_sizes, product_price

urlpatterns = [
    path('<str:category>/<str:slug>/', product_detail_view, name='product_detail'),
    path('<str:category>/<str:slug>/c<int:color>/', product_detail_view, name='product_variant'),
    path('<str:category>/<str:slug>/v<int:variant>/', product_detail_view, name='product_variant'),
    path('<str:category>/<str:slug>/c<int:color>/v<int:variant>/', product_detail_view, name='product_variant'),
    path('sizes/', product_sizes, name='product_sizes'),
    path('price/', product_price, name='product_price'),
    path('search/', search_view, name='search'),
]

shop/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    # Extensions
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # Custom
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include(('user.urls', 'user'), namespace="profiles")),
    path('order/', include(('order.urls', 'order'), namespace="orders")),
    path('product/', include(('product.urls', 'product'), namespace="products")),
    # Extensions
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('_nested_admin/', include('nested_admin.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shop/about.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    About
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/about.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="content_type-about">
        <div class="page-header">
            <h1 class="text__page-header">
                About
            </h1>
        </div>

        <div class="about__content-section">
            <div class="about__container">
                <div class="about__row">
                    <div class="about__col-text">
                        <div class="about__header">
                            <h3>Title</h3>
                        </div>
                        <div class="about__text">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquid animi
                                asperiores consequatur doloribus enim eum id minus, nam obcaecati odio saepe similique
                                tenetur veniam vero vitae, voluptas? At, facere.
                            </p>
                        </div>
                    </div>
                    <div class="about__col-img">
                        <img src="https://images.unsplash.com/photo-1612832164065-fc35ded2a291?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">
                    </div>
                </div>
                <div class="about__row">
                    <div class="about__col-text">
                        <div class="about__header">
                            <h3>Title</h3>
                        </div>
                        <div class="about__text">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquid animi
                                asperiores consequatur doloribus enim eum id minus, nam obcaecati odio saepe similique
                                tenetur veniam vero vitae, voluptas? At, facere.
                            </p>
                        </div>
                    </div>
                    <div class="about__col-img">
                        <img src="https://images.unsplash.com/photo-1612832164065-fc35ded2a291?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">
                    </div>
                </div>
                <div class="about__row">
                    <div class="about__col-text">
                        <div class="about__header">
                            <h3>Title</h3>
                        </div>
                        <div class="about__text">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci aliquid animi
                                asperiores consequatur doloribus enim eum id minus, nam obcaecati odio saepe similique
                                tenetur veniam vero vitae, voluptas? At, facere.
                            </p>
                        </div>
                    </div>
                    <div class="about__col-img">
                        <img src="https://images.unsplash.com/photo-1612832164065-fc35ded2a291?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="">
                    </div>
                </div>
            </div>
        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>

{% endblock %}

templates/shop/blog.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Blog
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/blog.css' %}"              rel="stylesheet">
    <link href="{% static 'css/cards/blog_card.css' %}"         rel="stylesheet">
    <link href="{% static 'css/components/pagination.css' %}"   rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="content_type-blog">
        <div class="page-header">
            <h1 class="text__page-header">
                Our blog
            </h1>
        </div>

        <div class="blog__content-section">
            <div class="blog-posts-container">
                <div class="blog-posts-container__card-wrapper">

                    {% for post in posts %}

                        {% include 'include/blog_card.html' %}

                    {% endfor %}


                    {% include 'include/pagination.html' %}

                </div>
            </div>
        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>
{% endblock %}

templates/shop/blog_post.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    {{ post.title }}
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/blog_post.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="content_type-blog-detail">
        <div class="page-header">
            <h1 class="text__page-header">
                {{ post.title }}
            </h1>
        </div>

        <div class="blog-detail__content-section">
            <div class="blog-detail__container">
                <div class="blog-detail__description">
                    {{ post.preview_content }}
                </div>
                <div class="blog-detail__content">
                    {{ post.content | safe }}
                </div>
            </div>
        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>
{% endblock %}

templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Cart
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/cart.css' %}"                rel="stylesheet">
    <link href="{% static 'css/cards/product_cart_card.css' %}"   rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="content_type-cart">
        <div class="page-header">
            <h1 class="text__page-header">
                Cart
            </h1>
        </div>

        <div class="cart__content-section">
            <div class="cart-products-container">
                <div class="cart-products-container__card-wrapper">

                    {% for cart_product in cart_products %}

                        {% include 'include/product_cart_card.html' %}

                    {% endfor %}

                </div>
            </div>

            <div class="cart__summary-container">
                <div class="cart__summary-qty">
                    <p>TOTAL: {{ cart.total_products }}</p>
                </div>
                <div class="cart__summary-priceAndBtn">
                    <div class="cart__summary-final-price">
                        <p>{{ cart.final_price }}$</p>
                    </div>
                    <a href="{% url 'orders:checkout' %}">
                        <button class="action-btn">Submit</button>
                    </a>
                </div>
            </div>

        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
{% endblock %}

templates/shop/categories.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Categories
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/categories.css' %}"      rel="stylesheet">
    <link href="{% static 'css/cards/category_card.css' %}"   rel="stylesheet">
{% endblock %}

{% block content %}
<div class="content_type-categories">

    <div class="page-header">
        <h1 class="text__page-header">
            CATEGORIES
        </h1>
    </div>

    <div class="categories__slider-container"></div>
    <div class="categories__content-section">
        <div class="categories-container">
            <div class="categories-container__card-wrapper">

                {% for category in categories %}

                    {% include 'include/category_card.html' %}

                {% endfor %}

            </div>
        </div>
    </div>

    <div class="background-circle--top"></div>
    <div class="background-circle--bottom"></div>

</div>
{% endblock %}

templates/shop/category_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Category {{ category.name }}
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/category_detail.css' %}"       rel="stylesheet">
    <link href="{% static 'css/cards/category_product_card.css' %}" rel="stylesheet">
    <link href="{% static 'css/cards/category_product_card.css' %}" rel="stylesheet">
    <link href="{% static 'css/components/filter.css' %}"           rel="stylesheet">
    <link href="{% static 'css/components/pagination.css' %}"       rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="content_type-products">

        <div class="page-header">
            <div class="page-header__filter-container">
                <button class="filter-btn"></button>
            </div>
            <h1 class="text__page-header">
                {{ category.name.upper }}
            </h1>
        </div>

        {% include 'include/filter.html' %}

    
        <div class="products__slider-container"></div>
        <div class="products__content-section">
            <div class="products-container">
                <div class="products-container__card-wrapper">

                    {% for record in category_products %}

                        {% include 'include/category_product_card.html' %}

                    {% endfor %}

                </div>


                {% include 'include/pagination.html' %}
            </div>
        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>

    <script>
        let priceMinCategory = {{ category_price_min }};
        let priceMaxCategory = {{ category_price_max }};

        let priceMin = 1;
        let priceMax = 1;

        if ({{ filter_form.price_min.value }} || {{ filter_form.price_max.value }}) {
            priceMin = {{ filter_form.price_min.value }};
            priceMax = {{ filter_form.price_max.value }};
        }


    </script>
{% endblock %}


{% block js %}
    <script src="{% static 'js/nouislider.js' %}"></script>
    <script src="{% static 'js/filter.js' %}"></script>
    <script src="{% static 'js/category_detail.js' %}" type="text/javascript"></script>
{% endblock %}

templates/shop/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
    Checkout
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/checkout.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="content_type-checkout">
        <div class="page-header">
            <h1 class="text__page-header">
                Checkout
            </h1>
        </div>

        <div class="checkout__content-section">
            <div class="checkout__container">

                <div class="checkout__form">

                    <form action="{% url 'orders:make_order' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-field checkout__form-field">
                            {{ form.first_name }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ form.last_name }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ form.phone }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ form.comment }}
                        </div>

                        <h3>Shipping</h3>
                        <div class="form-field checkout__form-field">
                          <p>Approximate delivery time</p>
                          {{ delivery_date }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ formset.address }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ formset.city }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ formset.region }}
                        </div>
                        <div class="form-field checkout__form-field">
                            {{ formset.zipcode }}
                        </div>
                        <input type="submit" class="action-btn" value="Submit">
                    </form>

                </div>

            </div>
        </div>

    </div>

{% endblock %}

templates/shop/faq.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    FAQ
{% endblock %}

{% block styles %}
    <link href="{% static 'css/pages/faq.css' %}" rel="stylesheet">
    <link href="{% static 'css/extensions/accordion.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="content_type-faq">
        <div class="page-header">
            <h1 class="text__page-header">
                FAQ
            </h1>
        </div>

        <div class="faq__content-section">
            <div class="faq__container">

                <div class="accordion-container">
                    {% for f in faq %}
                    <div class="ac">
                        <h2 class="ac-header">
                            <button class="ac-trigger">
                                {{ f.question }}
                            </button>
                        </h2>
                        <div class="ac-panel">
                            <p class="ac-text">
                                {{ f.answer }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>

        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>

    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/accordion.js' %}"></script>
    <script src="{% static 'js/faq.js' %}"></script>
{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    {{ product.title }}
{% endblock %}

{% block styles %}
    <!-- Splide css -->
    <link rel="stylesheet" href="{% static 'css/extensions/splide.min.css' %}">

    <link href="{% static 'css/extensions/splideCustom.css' %}"  rel="stylesheet">
    <link href="{% static 'css/pages/product_detail.css' %}"    rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="content_type-prod-detail">

        <div class="product-photoviewer-specification-row">

            <div class="product__photoviewer-container">
                <div class="product__photoviewer">

                    <div class="product__photoviewer__viewer">
                        <div id="primary-slider" class="splide">
                            <div class="splide__track">
                                <ul class="splide__list">
                                    {% for photo in product_images %}
                                    <li class="splide__slide">
                                        <img src="{{ photo.image.url }}">
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="product__photoviewer__carousel">
                        <div id="secondary-slider" class="splide">
                            <div class="splide__track">
                                <ul class="splide__list">
                                    {% for photo in product_images %}
                                        <li class="splide__slide">
                                            <img src="{{ photo.image.url }}">
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="prod-detail__product-specification-container">
                <div class="product-about">
                    {% if product.variant == 'None' %}
                        <div class="product-about__header-container">
                            <h2>{{ product.title }}</h2>
                        </div>
                    {% else %}
                        <div class="product-about__header-container">
                            <h2>{{ variant.title }}</h2>
                        </div>
                    {% endif %}

                    {% if product.variant == 'None' %}

                        <div class="product-about__price-container">
                            {% if product.discount_price %}
                                <h2><del>{{ product.price }} $</del></h2>
                                <h4 class="text--red">{{ product.discount_price }} $</h4>
                            {% else %}
                                <h4>{{ product.price }} $</h4>
                            {% endif %}
                        </div>
                        <div class="product-about__common-description-container">
                            <p class="product-about__common-description">
                                {{ product.description | safe }}
                            </p>
                        </div>

                    {% elif product.variant == 'Size-Color' %}

                        <div class="product-about__price-container">
                            {% if variant.discount_price %}
                                <h2><del>{{ variant.price }} $</del></h2>
                                <h4 class="text--red">{{ variant.discount_price }} $</h4>
                            {% else %}
                                <h4>{{ variant.price }} $</h4>
                            {% endif %}
                        </div>
                        <div class="product-about__common-description-container">
                            <p class="product-about__common-description">
                                {{ product.description | safe }}
                            </p>
                        </div>

                        <div class="product-options">

                            <div class="product-about__chooser-container chooseColor">
                                <ul class="product-tile__colors-list">
                                    {% for c in colors %}
                                        <a href="{% url 'product:product_variant' category=product.category.slug slug=product.slug color=c.color.id  %}" class="color-value" data-product_id="{{ product.id }}" data-variant_id="{{ c.id }}" data-color_id="{{ c.color.id }}">
                                            <li class="product-tile__colors-item">
                                                <a href="{% url 'product:product_variant' category=product.category.slug slug=product.slug color=c.color.id  %}"
                                                   data-product_id="{{ product.id }}"
                                                   data-variant_id="{{ c.id }}"
                                                   data-color_id="{{ c.color.id }}"
                                                   class="product-tile__colors-link {% if c.color.id == variant.color.id %} product-tile__colors-link_state_active {% endif %}">
                                                    <span class="product-tile__colors-content" style="background-color: {{ c.color.code }}">
                                                    </span>
                                                </a>
                                            </li>
                                        </a>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="product-about__chooser-container">
                                <select name="size" id="product_size" class="product__chooser" onchange="location = this.value;">
                                    {% for s in sizes %}
                                        <option {% if variant.id == s.id %} selected {% endif %} value="{% url 'product:product_variant' category=product.category.slug slug=product.slug variant=s.id  %}" data-product_id="{{ product.id }}" data-variant_id="{{ s.id }}">
                                            {{ s.size.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>

                    {% elif product.variant == 'Size' %}

                        <div class="product-about__price-container">
                            {% if variant.discount_price %}
                                <h2><del>{{ variant.price }} $</del></h2>
                                <h4 class="text--red">{{ variant.discount_price }} $</h4>
                            {% else %}
                                <h4>{{ variant.price }} $</h4>
                            {% endif %}
                        </div>
                        <div class="product-about__common-description-container">
                            <p class="product-about__common-description">
                                {{ product.description | safe }}
                            </p>
                        </div>

                        <div class="product-options">

                            <div class="product-about__chooser-container">
                                <select name="size" id="product_size" class="product__chooser" onchange="location = this.value;">
                                    {% for s in sizes %}
                                        <option {% if variant.id == s.id %} selected {% endif %} value="{% url 'product:product_variant' category=product.category.slug slug=product.slug variant=s.id  %}" data-product_id="{{ product.id }}" data-variant_id="{{ s.id }}">
                                            {{ s.size.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>

                    {% elif product.variant == 'Color' %}

                        <div class="product-about__price-container">
                            {% if variant.discount_price %}
                                <h2><del>{{ variant.price }} $</del></h2>
                                <h4 class="text--red">{{ variant.discount_price }} $</h4>
                            {% else %}
                                <h4>{{ variant.price }} $</h4>
                            {% endif %}
                        </div>
                        <div class="product-about__common-description-container">
                            <p class="product-about__common-description">
                                {{ product.description | safe }}
                            </p>
                        </div>

                        <div class="product-options">

                            <div class="product-about__chooser-container chooseColor">
                                <ul class="product-tile__colors-list">
                                    {% for c in colors %}
                                            <li class="product-tile__colors-item">
                                                <a href="{% url 'product:product_variant' category=product.category.slug slug=product.slug color=c.color.id variant=c.id  %}"
                                                   data-product_id="{{ product.id }}"
                                                   data-variant_id="{{ c.id }}"
                                                   data-color_id="{{ c.color.id }}"
                                                   class="product-tile__colors-link {% if c.color.id == variant.color.id %} product-tile__colors-link_state_active {% endif %}">
                                                    <span class="product-tile__colors-content" style="background-color: {{ c.color.code }}">
                                                    </span>
                                                </a>
                                            </li>
                                    {% endfor %}
                                </ul>
                            </div>

                        </div>

                    {% endif %}

                    <div class="product__buy-button-container">
                        {% if product.variant == 'None' %}
                            <a href="{% url 'orders:add_to_cart' category=product.category.slug slug=product.slug %}">
                                <button class="buy-button text--red" data-goods_id="{{ product.id }}" data-action="addToCart">TO CART</button>
                            </a>
                        {% else %}
                            <a href="{% url 'orders:add_to_cart' category=product.category.slug slug=product.slug variant=variant.id %}">
                                <button class="buy-button text--red" data-goods_id="{{ product.id }}" data-action="addToCart">TO CART</button>
                            </a>
                        {% endif %}
                    </div>
                    <div class="product__delivery-button-container">
                        <a href="{% url 'delivery_view' %}">
                            <p class="delivery-button">SHIPPING</p>
                        </a>
                    </div>
                </div>
            </div>

            {% include 'include/product_specifications.html' %}
        </div>


        <div class="background-circle--top"></div>
        <div class="background-circle--bottom"></div>
    </div>

{% endblock content %}

{% block js %}
    <!-- Custom js -->
    <script src="{% static 'js/product_detail.js' %}"></script>

    <!-- Splide JS -->
    <script type="text/javascript" src="{% static 'js/splide.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/splideCustom.js' %}"></script>
{% endblock %}